server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: weezam-gateway
  cloud:
    gateway:
      routes:
      - id: userModule
        uri: lb://WEEZAM-USER
        predicates:
          - Path=/users/**
      - id: withdrawalModule
        uri: lb://WEEZAM-WITHDRAWAL
        predicates:
          - Path=/withdrawals/**